runtime: java17
instance_class: F1
entrypoint: java -jar build/libs/currencywidget-0.0.1-SNAPSHOT.jar
automatic_scaling:
  max_instances: 3
  max_concurrent_requests: 10
env_variables:
  DB_USERNAME: currencyserveruser
  DB_PASSWORD: MB|~S(bDqEPMV(H-
  DB_NAME: currencywidgetdb
  INSTANCE_CONNECTION_NAME: currencywidgetserver:europe-central2:currencydatabase


